name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  # Backend Job
  backend:
    runs-on: ubuntu-latest
    working-directory: ./backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js for Backend
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Backend Dependencies
        run: npm install

      - name: Run Backend Linter
        run: npm run lint

      - name: Run Backend Tests
        run: npm test

  # Frontend Job
  frontend:
    runs-on: ubuntu-latest
    working-directory: ./frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Frontend Dependencies
        run: npm install

      - name: Run Frontend Linter
        run: npm run lint

      - name: Build Frontend
        run: npm run build

  # Deployment Job
  deploy:
    needs: [frontend, backend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy Backend and Frontend
        run: |
          echo "Deploying both backend and frontend"
          # You can deploy to Render, Railway, or AWS here.
